// frontend/src/components/UserStatBlock.svelte
<script lang='ts'>
  import { blur } from 'svelte/transition'

  export let rank: number
  export let userStats: UserStats

</script>

<style>
  .user-stat-block {
    margin-bottom: 1rem;
  }

  .user-stat-block a {
    background-color: white;
    border: 1px solid hsl(0, 0%, 78%);
    border-radius: 8px;
    padding: 1rem 2rem;
    display: grid;
    grid-gap: 2rem;
    grid-template-columns: 3.75rem 6rem 8.365rem 3fr;
    grid-template-areas: "rank avatar name stats";
    text-decoration: none;
    color: initial;
    transition: box-shadow .2s ease-in-out, transform .2s ease-in-out;
  }

  .user-stat-block a:hover {
    box-shadow: 0px 0px 13px 0px rgba(0, 0, 0, 0.1);
    transform: translateY(-2px);
  }

  .rank {
    font-size: 2rem;
    opacity: 0.8;
    grid-area: rank;
    align-self: center;
  }

  .avatar {
    border-radius: 50%;
    width: 6rem;
    height: 6rem;
    grid-area: avatar;
    align-self: center;
  }

  .name {
    grid-area: name;
    align-self: center;
  }

  .stat-block {
    grid-area: stats;
    align-self: center;
  }

  .emoji-stat-light {
    font-size: 1.25rem;
    margin-right: 1rem;
    opacity: 0.8;
  }
</style>

<li class="user-stat-block" in:blur>
  <a href="https://github.com/{userStats.user}" target="_blank">
    <p class="rank">#{rank}</p>
    <img class="avatar" src="{userStats.avatarUrl}" alt="{userStats.user}'s Profile Image">
    <p class="name">{userStats.user}</p>
    <div class="stat-block">
      <p><span class="emoji-stat-light">⚔️️️️️️</span>+{userStats.additions}&emsp;-{userStats.deletions}</p>
      <p><span class="emoji-stat-light">💾</span>{userStats.commits} {userStats.commits === 1 ? 'Commit' : 'Commits'}</p>
      <p>{userStats.userId}</p>
    </div>
  </a>
</li>

// src/components/userStatBlock/index.tsx
import styled from '@emotion/styled'

import Card from '../card'
import Emoji from '../emoji'

interface Props {
  rank: number | string
  userStats: UserStats
}

export default function UserStatBlock({ rank, userStats }: Props) {
  return (
    <Card>
      <$Content>
        <$Rank>#{rank}</$Rank>
        <$User>
          <a
            href={`https://www.github.com/${userStats.user}`}
            target="_blank"
            rel="noopener noreferrer"
          >
            <img src={userStats.avatarUrl} alt={`${userStats.user}'s avatar`} />
          </a>
          <a
            href={`https://www.github.com/${userStats.user}`}
            target="_blank"
            rel="noopener noreferrer"
          >
            {userStats.user}
          </a>
        </$User>
        <$Stats>
          <div>
            <Emoji as="⚔️" aria-label="crossing-swords" />+{userStats.additions}
            &emsp;-
            {userStats.deletions}
          </div>
          <div>
            <Emoji as="💾" aria-label="floppy" />
            {userStats.commits} {userStats.commits === 1 ? 'Commit' : 'Commits'}
          </div>
        </$Stats>
      </$Content>
    </Card>
  )
}

const $Content = styled("li")`
  display: grid;
  gap: var(--space-5);
  grid-template-columns: var(--space-6) 1fr 1fr;
  grid-template-areas: 'rank user stats';
  align-items: center;
  @media screen and (max-width: 1024px) {
    grid-template-columns: min-content 1fr;
    grid-template-areas: 'rank user' 'rank stats';
    justify-content: center;
    row-gap: var(--space-4);
    column-gap: 0;
  }
  a {
    text-decoration: none;
  }
  a:hover {
    text-decoration: underline;
  }
`

const $Rank = styled("span")`
  font-size: var(--h3);
  opacity: 0.8;
  grid-area: rank;
`

const $User = styled("div")`
  grid-area: user;
  display: flex;
  align-items: inherit;
  @media screen and (max-width: 1024px) {
    flex-direction: column;
  }
  img {
    border-radius: 50%;
    width: 6rem;
    height: 6rem;
    @media screen and (min-width: 1025px) {
      margin-right: var(--space-5);
    }
    @media screen and (max-width: 1024px) {
      width: 4rem;
      height: 4rem;
    }
  }
`

const $Stats = styled("div")`
  grid-area: stats;
  display: grid;
  gap: var(--space-3);
  @media screen and (max-width: 1024px) {
    justify-content: center;
  }

  span {
    font-size: var(--h5);
    margin-right: var(--space-3);
    opacity: 0.8;
  }
`
