// src/routes/raids/ViewRaid.tsx
import React, { useEffect, useState } from 'react'
import firestore from '#utils/firebase'
import { useParams } from 'react-router-dom'

import styled from '@emotion/styled'

import UserStatBlock from '#components/user-stat-block'
import Emoji from '#components/emoji'
import LoadingSpinner from '#components/loading-spinner'

type State = 'loading' | 'success' | 'not-found' | 'error'

const StatsView = styled.main`
  height: 100vh;
  display: grid;
  grid-template-rows: auto 1fr;
  > * {
    padding: 1rem;
  }
`

const Header = styled.header`
  background-color: white;
  border-bottom: 1px solid hsl(0, 0%, 78%);
  box-shadow: 0 2px 4px 0 hsla(0, 0%, 0%, 10%);
  > section {
    margin: 0 auto;
    max-width: 700px;
  }

  > section > h1 {
    font-size: 2rem;
    line-height: 3rem;
    margin-bottom: 2rem;
  }
`

const TotalStats = styled.div`
  display: flex;
  flex-direction: row;
  flex-wrap: wrap;

  > p {
    font-size: 1rem;
    margin-bottom: 0.5rem;
    white-space: nowrap;
    > * {
      margin-right: 1rem;
    }
  }

  > :not(:last-child) {
    margin-right: 1rem;
  }
`

const StatContainer = styled.ol`
  overflow-y: auto;
  > * {
    margin: 0 auto;
    margin-top: 1em;
    max-width: 700px;
  }
`

const ViewRaid = () => {
  const { raidId } = useParams<{ raidId: string }>()
  const [state, setState] = useState<State>('loading')
  const [error, setError] = useState<Error | null>(null)
  const [data, setData] = useState<ViewRaidData | null>(null)

  useEffect(() => {
    firestore
      .collection('raid-stats')
      .doc(raidId)
      .get()
      .then((snapshot) => {
        if (snapshot.exists) {
          setData(snapshot.data() as ViewRaidData)
          setState('success')
        } else {
          setState('not-found')
        }
      })
      .catch((error) => {
        setError(error)
        setState('error')
      })
  }, [raidId])

  if (state === 'loading') {
    return <p>Loading...</p>
  } else if (state === 'error') {
    return <p>{JSON.stringify(error)}</p>
  } else if (state === 'not-found') {
    return <p>Couldn`t find that Raid - did you fall into the wrong dungeon?</p>
  } else {
    return (
      <StatsView>
        <Header>
          <section>
            <h1>{data?.title}</h1>
            <TotalStats>
              <p>
                <Emoji as="🚀" aria-label="rocket" />{' '}
                {Object.keys(data?.contributors ?? {}).length} Contributors
              </p>
              <p>
                <Emoji as="💾" aria-label="floppy" /> {data?.commits}{' '}
                {(data?.commits ?? 0) === 1 ? 'Commit' : 'Commits'}
              </p>
              <p>
                <Emoji as="📃" aria-label="file" /> {data?.changedFiles} Changed
                Files
              </p>
              <p>
                <Emoji as="⚔️" aria-label="crossing-swords" /> +
                {data?.additions} -{data?.deletions}
              </p>
              <p>
                <Emoji as="🔥" aria-label="fire" />{' '}
                {(data?.additions ?? 0) - (data?.deletions ?? 0)} Net Deletions
              </p>
            </TotalStats>
          </section>
        </Header>
        <StatContainer>
          {Object.values(data?.contributors ?? {}).map((contributor, index) => (
            <UserStatBlock
              key={contributor.userId}
              rank={index + 1}
              userStats={contributor}
            />
          ))}
        </StatContainer>
      </StatsView>
    )
  }
}

export default ViewRaid

// frontend/src/routes/dungeons/raids/ViewRaid.svelte
<script lang="ts">
	import { useParams } from 'svelte-navigator'
	import firebase from 'firebase/app'

	import LoadingSpinner from '#components/LoadingSpinner.svelte'
	import UserStatBlock from '#components/UserStatBlock.svelte'

	import { fade } from 'svelte/transition'

	const params = useParams<{ id: string }>()

	const database = firebase.database()
	const dataPromise = database
		.ref(`/${$params.id}`)
		.once('value')
		.then((snapshot) => snapshot.val() as ViewRaidData)

	const userStatSorts: {
		[key: string]: (a: UserStats, b: UserStats) => number
	} = {
		commits: (a, b) => b.commits - a.commits,
		additions: (a, b) => b.additions - a.additions,
		deletions: (a, b) => b.deletions - a.deletions,
	}
	const userStatSortNames = Object.keys(userStatSorts)

	let currentSort = userStatSortNames[0]
</script>

<main id="stats-view">
	{#await dataPromise}
		<LoadingSpinner />
	{:then data}
		<header in:fade>
			<div class="content">
				<h1>{data.title}</h1>
				<div class="total-stats">
					<div>
						<p>
							<span class="emoji-stat">🚀</span>{`${
								Object.keys(data.contributors).length
							}`} Contributors
						</p>
						<p>
							<span class="emoji-stat">💾</span>{data.commits}
							{data.commits === 1 ? 'Commit' : 'Commits'}
						</p>
						<p>
							<span class="emoji-stat">📃</span>{data.changedFiles} Changed Files
						</p>
					</div>
					<div>
						<p>
							<span class="emoji-stat">⚔️</span
							>+{data.additions}&emsp;-{data.deletions}
						</p>
						<p>
							<span class="emoji-stat">🔥</span>{data.additions -
								data.deletions} Net Deletions
						</p>
					</div>
				</div>
				Sort by:<select bind:value={currentSort} disabled={data.commits <= 1}>
					{#each userStatSortNames as theSort}
						<option value={theSort}>
							{theSort}
						</option>
					{/each}
				</select>
			</div>
		</header>

		<div class="stat-container">
			<ol id="stats" in:fade>
				{#each Object.values(data.contributors).sort(userStatSorts[currentSort]) as userStat, index (index + userStat.userId)}
					<UserStatBlock rank={index + 1} userStats={userStat} />
				{/each}
			</ol>
		</div>
	{:catch error}
		<p>{error.message}</p>
	{/await}
</main>

<style>
	#stats-view {
		height: 100vh;
		display: grid;
		grid-template-rows: auto 1fr;
	}
	#stats-view > * {
		padding: 1rem;
	}

	header {
		z-index: 1;
		background-color: white;
		border-bottom: 1px solid hsl(0, 0%, 78%);
		box-shadow: 0 2px 4px 0 hsla(0, 0%, 0%, 10%);
	}
	header > .content {
		margin: 0 auto;
		width: 700px;
	}

	h1 {
		font-size: 3rem;
		line-height: 3rem;
		margin-bottom: 2rem;
	}

	.total-stats {
		display: flex;
		direction: row;
	}
	.total-stats > :first-child {
		width: 23.5rem;
	}
	.total-stats > :not(:first-child) {
		margin-left: 2rem;
	}

	select {
		margin-top: 2rem;
		border: none;
		background-color: inherit;
		font-size: 1em;
		text-transform: capitalize;
	}

	.stat-container {
		overflow-y: auto;
	}
	.stat-container > * {
		margin: 0 auto;
		width: 700px;
	}
	.emoji-stat {
		font-size: 1.5rem;
		margin-right: 1rem;
	}
</style>
