// frontend/src/components/LoadingSpinner.svelte
<script>
  import { fade } from 'svelte/transition'
</script>

<div class="lds-background" out:fade>
  <div aria-label="Loading" class="lds-ellipsis">
    <div />
    <div />
    <div />
    <div />
  </div>
</div>

<style>
  .lds-background {
    background-color: hsla(0, 0%, 97%, 50%);
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
  }
  .lds-ellipsis {
    display: inline-block;
    position: absolute;
    z-index: 1;
    width: 80px;
    height: 80px;
    left: calc(50% - 40px);
    top: calc(50% - 40px);
  }
  .lds-ellipsis div {
    position: absolute;
    top: 33px;
    width: 13px;
    height: 13px;
    border-radius: 50%;
    background: hsl(0, 0%, 25%);
    animation-timing-function: cubic-bezier(0, 1, 1, 0);
  }
  .lds-ellipsis div:nth-child(1) {
    left: 8px;
    animation: lds-ellipsis1 0.6s infinite;
  }
  .lds-ellipsis div:nth-child(2) {
    left: 8px;
    animation: lds-ellipsis2 0.6s infinite;
  }
  .lds-ellipsis div:nth-child(3) {
    left: 32px;
    animation: lds-ellipsis2 0.6s infinite;
  }
  .lds-ellipsis div:nth-child(4) {
    left: 56px;
    animation: lds-ellipsis3 0.6s infinite;
  }
  @keyframes lds-ellipsis1 {
    0% {
      transform: scale(0);
    }
    100% {
      transform: scale(1);
    }
  }
  @keyframes lds-ellipsis3 {
    0% {
      transform: scale(1);
    }
    100% {
      transform: scale(0);
    }
  }
  @keyframes lds-ellipsis2 {
    0% {
      transform: translate(0, 0);
    }
    100% {
      transform: translate(24px, 0);
    }
  }
</style>

// src/components/loadingSpinner/index.tsx
import React from 'react'
import styled from '@emotion/styled'

export default function LoadingSpinner() {
  return (
    <Background>
      <Ellipsis aria-label="loading">
        <div></div>
        <div></div>
        <div></div>
        <div></div>
      </Ellipsis>
    </Background>
  )
}

const Background = styled.div`
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-color: hsla(0, 0%, 97%, 50%);
  z-index: 10;
`
const Ellipsis = styled.div`
  --ellipsis-size: 13px;
  --base-left-pos: 8px;
  --animation-settings: 0.6s infinite;

  position: absolute;
  top: 50%;
  left: 50%;
  display: inline-block;
  width: 80px;
  height: var(--ellipsis-size);
  transform: translate(-50%, -50%);

  div {
    position: absolute;
    width: var(--ellipsis-size);
    height: var(--ellipsis-size);
    background: var(--gray-500);
    border-radius: 50%;
    animation-timing-function: cubic-bezier(0, 1, 1, 0);

    &:nth-of-type(1) {
      left: var(--base-left-pos);
      animation: lds-ellipsis1 var(--animation-settings);
    }
    &:nth-of-type(2) {
      left: var(--base-left-pos);
      animation: lds-ellipsis2 var(--animation-settings);
    }
    &:nth-of-type(3) {
      left: calc(var(--base-left-pos) * 4);
      animation: lds-ellipsis2 var(--animation-settings);
    }
    &:nth-of-type(4) {
      left: calc(var(--base-left-pos) * 7);
      animation: lds-ellipsis3 var(--animation-settings);
    }
  }

  @keyframes lds-ellipsis1 {
    0% {
      transform: scale(0);
    }
    100% {
      transform: scale(1);
    }
  }
  @keyframes lds-ellipsis3 {
    0% {
      transform: scale(1);
    }
    100% {
      transform: scale(0);
    }
  }
  @keyframes lds-ellipsis2 {
    0% {
      transform: translate(0, 0);
    }
    100% {
      transform: translate(calc(var(--base-left-pos) * 3), 0);
    }
  }
`
